import { useEffect, useState } from "react";
import { useRouter } from "next/dist/client/router";
import styles from "../../../../../styles/Search.module.css";
import { BsFillPeopleFill, BsFillBagFill } from "react-icons/bs";
import { GiCarDoor } from "react-icons/gi";
import { AiOutlineCar } from "react-icons/ai";
import Head from "next/head";

function Search() {
  const [token, setToken] = useState();
  const [content, setContent] = useState([]);

  const router = useRouter();

  const credentials =
    '{\r\n    "agencyId": "DQgPjq82EpDunKRGv",\r\n    "agencyKey": "wnaurtm4FIGFV9QZ7hjTvkNfNRHKkE/w7XzbsL4sSMCdYuvVDT8JRJ3PArlbQJZpTFZIyg5oQmxUsujV0DS8TA==",\r\n    "clientId": "https://test.destinojet.co"\r\n}';

  const search = JSON.stringify({
    PickUpLocation: {
      cityCode: "MIA",
      continentCode: 0,
      countryCode: "US",
      region: "unitedStates",
      id: "cd10124d-9c05-499d-ba4f-973937542744",
      name: "Miami Intl",
      provider: "",
      latitude: 25.793,
      longitude: -80.291,
    },
    DropOffLocation: {
      cityCode: "MIA",
      continentCode: 0,
      countryCode: "US",
      region: "unitedStates",
      id: "cd10124d-9c05-499d-ba4f-973937542744",
      name: "Miami Intl",
      provider: "",
      latitude: 25.793,
      longitude: -80.291,
    },
    PickUpDate: router.query.PickUpDate,
    PickUpTime: "0930",
    DropOffDate: router.query.Search,
    DropOffTime: "0930",
    RateTypeCode: 0,
    CarCategoryType: 0,
    PaymentType: 0,
    corporateDiscount: "0",
    AgencyUrl: "test.destinojet.co",
  });

  useEffect(() => {
    fetch("https://auth-testing.smartlinks.dev/api/auth/agency/token", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: credentials,
    })
      .then((res) => res.json())
      .then((token) => setToken(token));
  }, []);
  useEffect(() => {
    if (token) {
      fetch("https://search-testing.smartlinks.dev/api/cars/search", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: search,
      })
        .then((res) => res.json())
        .then((search) => {
          setContent(search);
        });
    }
  }, [token]);

  return (
    <>
      <Head>
        <title>Busqueda</title>
        <meta name="search" content="Generated by BoniNeutron" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.greeting}>
        <h1>Hola Pedro,</h1>
        <p>Ahorra hasta un 30% agregando un auto en tu viaje a Chicago.</p>
      </div>
      <div className={styles.content}>
        {content.map((car, index) => {
          return (
            <div key={index} className={styles.carLabel}>
              <div className={styles.carImage}>
                <img src={car.imageUrl} alt="car" />
                <p>
                  {car.category === "Economic" && "12%"}
                  {car.category === "Compact" && "15%"}
                  {car.category === "Intermediate" && "18%"}
                  {car.category === "Full Size" && "20%"}
                  {car.category === "Standard" && "10%"}
                </p>
              </div>
              <div className={styles.carContent}>
                <img
                  className={styles.companyImageUrl}
                  src={car.companyImageUrl}
                  alt="company"
                />
                <div className={styles.model}>
                  <h2>{car.category}</h2>
                  <p>{car.model}</p>
                </div>
                <div className={styles.contIcons}>
                  <div className={styles.icons}>
                    <BsFillPeopleFill className={styles.icon} />
                    <p>{car.passengers}</p>
                  </div>
                  <div className={styles.icons}>
                    <GiCarDoor className={styles.icon} />
                    <p>{car.doors}</p>
                  </div>
                  <div className={styles.icons}>
                    <BsFillBagFill className={styles.icon} />
                    <p>3</p>
                  </div>
                </div>
                <div>
                  <div className={styles.splitIcon}>
                    <AiOutlineCar />
                  </div>
                  <div className={styles.line}></div>
                </div>
                <div className={styles.price}>
                  <div className={styles.usd}>
                    <h3>USD {car.dailyRate.toFixed(2)}</h3>
                    <p>/dia</p>
                  </div>
                  <p>
                    USD {car.totalRate.toFixed(2)} /
                    {(car.totalRate / car.dailyRate).toFixed(0)} dias
                  </p>
                </div>
              </div>
              <div className={styles.button}>
                <button>Reservar</button>
              </div>
            </div>
          );
        })}
      </div>
      <div className={styles.by}>
        <p>Powered by</p>
        <img
          src="https://res.cloudinary.com/ultragroup/image/upload/c_limit,h_100,w_200/utr8aiyycdl7iv9ahpjl"
          alt="logo"
        />
      </div>
    </>
  );
}

export default Search;
