import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.message}>
        <h1>Para que le la busqueda funcione, hay que agregarle a esta url:</h1>
        <h2>
          travelbyboni.vercel.app/ challenge/mia/mia/(fecha de recogida)/(fecha
          de entrega)
        </h2>
        <h3>Parametros de fecha:</h3>
        <h3>(fecha de recogida): 2021-12-03 // año-mes-dia</h3>
        <h3>(fecha de entrega): 2021-12-24 // año-mes-dia</h3>
        <h3>Debe quedar asi:</h3>
        <h2>
          travelbyboni.vercel.app/ challenge/mia/mia/2021-12-05/2021-12-24
        </h2>
        <h1>
          importante, la fecha de recogida no puede ser menor al dia actual!
        </h1>
      </div>
    </div>
  );
}
